In [2]:
import numpy as np
from sklearn.impute import SimpleImputer

In [4]:
# dataset with missing values
X = np.array([[1,2],
             [np.nan,3],
             [7,6]])
X

array([[ 1.,  2.],
       [nan,  3.],
       [ 7.,  6.]])

In [5]:
type(X)

numpy.ndarray

##### Instantiate the imputer with the strategy to use (mean, median, most_frequent, or constant)

In [7]:
imputer = SimpleImputer(strategy='mean')

In [8]:
# # Fit the imputer on the dataset
imputer.fit(X)

SimpleImputer(copy=True, fill_value=None, missing_values=nan, strategy='mean',
       verbose=0)

In [9]:
# # Transform the dataset, replacing missing values with the computed imputation values
X_imputed = imputer.transform(X)

In [10]:
print("Original Dataset")
X

Original Dataset


array([[ 1.,  2.],
       [nan,  3.],
       [ 7.,  6.]])

In [11]:
print("Imputed Dataset")
X_imputed

Imputed Dataset


array([[1., 2.],
       [4., 3.],
       [7., 6.]])