Ordinal encoding

In [27]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv('/content/sample_data/customer.csv')
data.head(10)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes
6   18    Male     Good    School        No
7   60  Female     Poor    School       Yes
8   65  Female  Average        UG        No
9   74    Male     Good        UG       Yes

In [29]:
df = data.iloc[:,2:]

In [30]:
df.head(5)

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [32]:
X_train

review education
12     Poor    School
4   Average        UG
10     Good        UG
27     Poor        PG
7      Poor    School
18     Good    School
17     Poor        UG
29  Average        UG
14     Poor        PG
2      Good        PG
36     Good        UG
11     Good        UG
3      Good        PG
24  Average        PG
45     Poor        PG
33     Good        PG
13  Average    School
46     Poor        PG
35     Poor    School
1      Poor        UG
43     Poor        PG
5   Average    School
6      Good    School
25     Good    School
8   Average        UG
20  Average    School
28     Poor    School
16     Poor        UG
21  Average        PG
38     Good    School
0   Average    School
22     Poor        PG
39     Poor        PG
47     Good        PG
40     Good    School
34  Average    School
49     Good        UG
19     Poor        PG
23     Good    School
26     Poor        PG

In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [34]:
oe= OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [35]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [36]:
x_train = oe.transform(X_train)

In [37]:
x_train

array([[0., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.]])

In [38]:
x_test = oe.transform(X_test)

In [39]:
x_test

array([[0., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [2., 1.]])

In [40]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()

In [43]:
le.fit(y_train)

LabelEncoder()

In [44]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [45]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [46]:
y_train

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0])

In [47]:
y_test

array([1, 1, 0, 0, 1, 1, 1, 0, 1, 1])